### ISSUE TITLE
Peer Code Review 

### ISSUE THREAD

**Issue by amiraabouhadid** [iLynette/todo-list#5]
Hey Lynette, 
Good job separating the DOM manipulation from the logic.
Here are a few things missing in your testing fille:

- [x] ** Create tests for edit todo 
- [x] ** Create tests for checking todos(i.e status update to completed todo)
- [x] ** Create tests for clearing all completed todos

Best of luck and great work!
![](https://media0.giphy.com/media/l3BwSPbqx3QGKEgpp2/200w.webp?cid=ecf05e476e3lbd0evinaj2rb4o1w58sck4h0sqnmyioczedk&rid=200w.webp&ct=g)

**Comment by zmekonnen251** [comment]
- You did a great job. your code is clean and organized. I have only one comment. your code can be modularized more.
